language: php

php:
  - "7.4"
  - "8.0"
  - "8.1"
  - "8.2"

os:
  - linux

addons:
  apt:
    packages:
      - dnsutils # dig ve nslookup için
      - coreutils # sort ve dirname için

before_script:
  - chmod +x chkdm.php

script:
  # Temel komutların varlığını kontrol et
  - command -v dig
  - command -v nslookup
  - command -v sed
  - command -v head
  - command -v awk
  - command -v sort
  - command -v dirname
  - command -v readlink

  # PHP syntax kontrolü
  - php -l chkdm.php
  - php -l index.php
  - php -l api.php

  # Örnek domain kontrolü
  - php chkdm.php example.com

  # Web sunucusu testi
  - php -S localhost:8000 &
  - sleep 3
  - curl -s http://localhost:8000 | grep "Domain Checker"

notifications:
  email:
    on_success: change
    on_failure: always
